using System.Text;

namespace Aprs.Desktop.Services;

/// <summary>
/// Generates ICS-213 General Message Forms from APRS messages.
///
/// ICS-213 is the FEMA/NIMS standard written message form used to document
/// radio messages during an incident. Some served agencies require that all
/// radio messages be recorded on ICS-213 forms for the incident record.
///
/// One ICS-213 form is generated per message. Multiple forms are separated
/// by page break markers so the output can be printed as individual forms.
///
/// Form fields per FEMA ICS-213 (October 2017 version):
///   Block 1  — To (name/position/radio unit ID)
///   Block 2  — From (name/position/radio unit ID)
///   Block 3  — Subject
///   Block 4  — Date/time of message
///   Block 5  — Message body
///   Block 6  — Approved by (signature block)
///   Block 7  — Reply
/// </summary>
public static class Ics213ExportService
{
    /// <summary>
    /// Generates one ICS-213 form per message, bundled in a single file
    /// with page separators between forms.
    /// </summary>
    public static string GenerateIcs213Bundle(
        string operatorCallsign,
        string operatorName,
        string incidentName,
        IReadOnlyList<Ics213Message> messages)
    {
        if (messages.Count == 0)
            return $"ICS-213 — No messages to document for incident: {incidentName}\n" +
                   $"Generated: {DateTimeOffset.Now.ToLocalTime():MM/dd/yyyy HH:mm}\n";

        var sb = new StringBuilder();

        for (int i = 0; i < messages.Count; i++)
        {
            sb.Append(GenerateSingleForm(operatorCallsign, operatorName, incidentName, messages[i], i + 1, messages.Count));

            if (i < messages.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine(Repeat('─', 72) + " [PAGE BREAK]");
                sb.AppendLine();
            }
        }

        sb.AppendLine();
        sb.AppendLine(Repeat('═', 72));
        sb.AppendLine(Center($"ICS-213 Bundle — {messages.Count} message form(s)", 72));
        sb.AppendLine(Center("Generated by APRS Command — github.com/KE4CON/APRS-Command", 72));
        sb.AppendLine(Repeat('═', 72));

        return sb.ToString();
    }

    private static string GenerateSingleForm(
        string operatorCallsign,
        string operatorName,
        string incidentName,
        Ics213Message msg,
        int formNumber,
        int totalForms)
    {
        var sb = new StringBuilder();

        sb.AppendLine(Repeat('═', 72));
        sb.AppendLine(Center($"ICS 213 — GENERAL MESSAGE FORM  ({formNumber} of {totalForms})", 72));
        sb.AppendLine(Center("FEMA / NIMS Incident Command System", 72));
        sb.AppendLine(Repeat('═', 72));
        sb.AppendLine();

        sb.AppendLine($"   Incident Name:  {incidentName}");
        sb.AppendLine();

        // Block 1 & 2: To / From
        sb.AppendLine(Repeat('─', 72));
        sb.AppendLine($"   1. TO:           {msg.ToCallsign}");
        sb.AppendLine($"   2. FROM:         {msg.FromCallsign}");
        sb.AppendLine(Repeat('─', 72));
        sb.AppendLine();

        // Block 3: Subject
        sb.AppendLine($"   3. SUBJECT:      APRS Radio Message");
        sb.AppendLine();

        // Block 4: Date/time
        var msgTime = (msg.ReceivedAtUtc ?? msg.SentAtUtc ?? msg.CreatedAtUtc).ToLocalTime();
        var direction = msg.IsOutbound ? "Transmitted (TX)" : "Received (RX)";
        sb.AppendLine($"   4. DATE/TIME:    {msgTime:MM/dd/yyyy  HH:mm}  [{direction}]");
        sb.AppendLine();

        // Block 5: Message
        sb.AppendLine("   5. MESSAGE:");
        sb.AppendLine(Repeat('─', 72));
        // Word-wrap message at 68 chars
        var words = msg.MessageBody.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var line  = new StringBuilder("   ");
        foreach (var word in words)
        {
            if (line.Length + word.Length + 1 > 71)
            {
                sb.AppendLine(line.ToString());
                line = new StringBuilder("   ");
            }
            if (line.Length > 3) line.Append(' ');
            line.Append(word);
        }
        if (line.Length > 3) sb.AppendLine(line.ToString());
        sb.AppendLine(Repeat('─', 72));
        sb.AppendLine();

        // Block 6: Approved by
        sb.AppendLine("   6. APPROVED BY:");
        sb.AppendLine($"      Name:      {operatorName}");
        sb.AppendLine($"      Callsign:  {operatorCallsign}");
        sb.AppendLine($"      Position:  Communications");
        sb.AppendLine($"      Date/Time: {DateTimeOffset.Now.ToLocalTime():MM/dd/yyyy HH:mm}");
        sb.AppendLine();

        // Block 7: Reply
        sb.AppendLine("   7. REPLY:");
        if (!string.IsNullOrWhiteSpace(msg.ReplyText))
        {
            sb.AppendLine($"      {msg.ReplyText}");
        }
        else
        {
            sb.AppendLine("      _______________________________________________");
            sb.AppendLine("      _______________________________________________");
        }
        sb.AppendLine();
        sb.AppendLine($"      Replied by: _________________________ Date/Time: ___________");
        sb.AppendLine();

        return sb.ToString();
    }

    private static string Repeat(char c, int n) => new(c, n);
    private static string Center(string s, int width) =>
        s.Length >= width ? s : s.PadLeft((width + s.Length) / 2).PadRight(width);
}

/// <summary>A single message for ICS-213 form generation.</summary>
public sealed record Ics213Message(
    string FromCallsign,
    string ToCallsign,
    string MessageBody,
    bool IsOutbound,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? SentAtUtc,
    DateTimeOffset? ReceivedAtUtc,
    string? ReplyText = null);
