using System.Text;

namespace Aprs.Desktop.Services;

/// <summary>
/// Generates an ICS-211 Incident Check-In List from the net control roster.
///
/// ICS-211 is the FEMA/NIMS standard form used to record all personnel and
/// resources checking in and out of an incident or event. It is completed
/// by the Check-In Recorder at each incident facility.
///
/// Form fields per FEMA ICS-211 (October 2017 version):
///   Block 1  — Incident name
///   Block 2  — Date/time prepared
///   Block 3  — Check-in location (facility/branch/division)
///   Block 4  — Resources (radio call sign, name, affiliation, time in/out, etc.)
///   Block 5  — Prepared by
/// </summary>
public static class Ics211ExportService
{
    /// <summary>
    /// Generates a plain-text ICS-211 Check-In List from roster entries.
    /// </summary>
    public static string GenerateIcs211(
        string incidentName,
        string operatorCallsign,
        string operatorName,
        string checkInLocation,
        DateTimeOffset periodFrom,
        DateTimeOffset periodTo,
        IReadOnlyList<Ics211RosterEntry> entries)
    {
        var sb  = new StringBuilder();
        var now = DateTimeOffset.Now;

        // ── Header ────────────────────────────────────────────────────────────
        sb.AppendLine(Repeat('═', 80));
        sb.AppendLine(Center("ICS 211 — INCIDENT CHECK-IN LIST", 80));
        sb.AppendLine(Center("FEMA / NIMS Incident Command System", 80));
        sb.AppendLine(Repeat('═', 80));
        sb.AppendLine();

        // ── Block 1 & 2 ───────────────────────────────────────────────────────
        sb.AppendLine($"1. INCIDENT NAME:        {incidentName}");
        sb.AppendLine($"2. DATE/TIME PREPARED:   {now.ToLocalTime():MM/dd/yyyy  HH:mm}");
        sb.AppendLine();

        // ── Block 3 ───────────────────────────────────────────────────────────
        sb.AppendLine($"3. CHECK-IN LOCATION:    {checkInLocation}");
        sb.AppendLine($"   Operational Period:   {periodFrom.ToLocalTime():MM/dd/yyyy HH:mm} — {periodTo.ToLocalTime():MM/dd/yyyy HH:mm}");
        sb.AppendLine();

        // ── Block 4: Resources ────────────────────────────────────────────────
        sb.AppendLine("4. RESOURCES:");
        sb.AppendLine(Repeat('─', 80));
        sb.AppendLine(
            $"   {"CALL SIGN / ID",-16} {"NAME / TACTICAL",-20} {"AFFILIATION",-16} {"TIME IN",-8} {"TIME OUT",-8} STATUS");
        sb.AppendLine(Repeat('─', 80));

        var checkedIn  = entries.Where(e => e.Status != "Not Checked In").OrderBy(e => e.CheckInTime).ToList();
        var notChecked = entries.Where(e => e.Status == "Not Checked In").OrderBy(e => e.Callsign).ToList();

        foreach (var entry in checkedIn.Concat(notChecked))
        {
            var callId   = Truncate(entry.Callsign, 15);
            var name     = Truncate(entry.TacticalLabel ?? entry.Callsign, 19);
            var org      = Truncate(entry.HomeAgency ?? string.Empty, 15);
            var timeIn   = entry.CheckInTime.HasValue
                ? entry.CheckInTime.Value.ToLocalTime().ToString("HH:mm")
                : "—";
            var timeOut  = entry.CheckOutTime.HasValue
                ? entry.CheckOutTime.Value.ToLocalTime().ToString("HH:mm")
                : "—";
            var status   = Truncate(entry.Status, 12);

            sb.AppendLine($"   {callId,-16} {name,-20} {org,-16} {timeIn,-8} {timeOut,-8} {status}");
        }

        sb.AppendLine(Repeat('─', 80));

        // Summary counts
        var checkedInCount  = entries.Count(e => e.Status == "Checked In");
        var standbyCount    = entries.Count(e => e.Status == "Standby");
        var departedCount   = entries.Count(e => e.Status == "Departed");
        sb.AppendLine($"   Checked In: {checkedInCount}  |  Standby: {standbyCount}  |  Departed: {departedCount}  |  Total: {entries.Count}");
        sb.AppendLine();

        // ── Block 5: Prepared by ──────────────────────────────────────────────
        sb.AppendLine("5. PREPARED BY (CHECK-IN RECORDER):");
        sb.AppendLine($"   Name:      {operatorName}");
        sb.AppendLine($"   Callsign:  {operatorCallsign}");
        sb.AppendLine($"   Date/Time: {now.ToLocalTime():MM/dd/yyyy HH:mm}");
        sb.AppendLine();

        // ── Footer ────────────────────────────────────────────────────────────
        sb.AppendLine(Repeat('═', 80));
        sb.AppendLine(Center("Generated by APRS Command — github.com/KE4CON/APRS-Command", 80));
        sb.AppendLine(Center("ICS 211 (October 2017) — Page 1 of 1", 80));
        sb.AppendLine(Repeat('═', 80));

        return sb.ToString();
    }

    private static string Repeat(char c, int n) => new(c, n);
    private static string Center(string s, int width) =>
        s.Length >= width ? s : s.PadLeft((width + s.Length) / 2).PadRight(width);
    private static string Truncate(string s, int max) =>
        s.Length <= max ? s : s[..(max - 1)] + "…";
}

/// <summary>A roster entry for ICS-211 generation.</summary>
public sealed record Ics211RosterEntry(
    string Callsign,
    string? TacticalLabel,
    string? HomeAgency,
    string Status,
    DateTimeOffset? CheckInTime,
    DateTimeOffset? CheckOutTime);
