using System.Text;

namespace Aprs.Desktop.Services;

/// <summary>
/// Generates an ICS-309 Communications Log from APRS Command session data.
///
/// ICS-309 is the FEMA/NIMS standard chronological log of every radio message
/// handled during an operational period — the form a served agency expects for
/// the incident communications record. Where ICS-213 captures one message per
/// form, ICS-309 lists them all in one time-ordered table.
///
/// Form fields per FEMA ICS-309:
///   Block 1  — Incident name
///   Block 2  — Operational period (date/time from/to)
///   Block 3  — Radio operator name / ICS position / callsign
///   Block 4  — Chronological log: Time, From, To, Subject/Message
///   Block 5  — Prepared by
/// </summary>
public static class Ics309ExportService
{
    /// <summary>
    /// Generates a plain-text ICS-309 Communications Log suitable for printing or filing.
    /// Only messages whose timestamp falls within the operational period are listed.
    /// </summary>
    public static string GenerateIcs309(
        string incidentName,
        string operatorName,
        string operatorCallsign,
        string icsPosition,
        DateTimeOffset periodFrom,
        DateTimeOffset periodTo,
        IReadOnlyCollection<AprsMessageSnapshot> messages)
    {
        var sb = new StringBuilder();
        var now = DateTimeOffset.Now;

        // ── Header ────────────────────────────────────────────────────────────
        sb.AppendLine(Repeat('═', 72));
        sb.AppendLine(Center("ICS 309 — COMMUNICATIONS LOG", 72));
        sb.AppendLine(Center("FEMA / NIMS Incident Command System", 72));
        sb.AppendLine(Repeat('═', 72));
        sb.AppendLine();

        // ── Block 1: Incident name ────────────────────────────────────────────
        sb.AppendLine("1. INCIDENT NAME:");
        sb.AppendLine($"   {incidentName}");
        sb.AppendLine();

        // ── Block 2: Operational period ───────────────────────────────────────
        sb.AppendLine("2. OPERATIONAL PERIOD:");
        sb.AppendLine($"   Date/Time From:  {periodFrom.ToLocalTime():MM/dd/yyyy  HH:mm}");
        sb.AppendLine($"   Date/Time To:    {periodTo.ToLocalTime():MM/dd/yyyy  HH:mm}");
        sb.AppendLine();

        // ── Block 3: Radio operator ───────────────────────────────────────────
        sb.AppendLine("3. RADIO OPERATOR (NAME / POSITION / CALLSIGN):");
        sb.AppendLine($"   {operatorName}   |   {icsPosition}   |   {operatorCallsign}");
        sb.AppendLine();

        // ── Block 4: Communications log ───────────────────────────────────────
        sb.AppendLine("4. COMMUNICATIONS LOG:");
        sb.AppendLine(Repeat('─', 72));
        sb.AppendLine($"   {"TIME",-14} {"FROM",-10} {"TO",-10} SUBJECT / MESSAGE");
        sb.AppendLine(Repeat('─', 72));

        var logged = messages
            .Where(m => m.TimestampUtc >= periodFrom && m.TimestampUtc <= periodTo)
            .OrderBy(m => m.TimestampUtc)
            .ToList();

        if (logged.Count == 0)
        {
            sb.AppendLine("   No messages recorded for this operational period.");
        }
        else
        {
            foreach (var m in logged)
            {
                var time = m.TimestampUtc.ToLocalTime().ToString("MM/dd HH:mm");
                var from = Truncate(m.FromCallsign, 10);
                var to = Truncate(m.ToCallsign, 10);
                var subject = Truncate(m.MessageText, 34);
                sb.AppendLine($"   {time,-14} {from,-10} {to,-10} {subject}");
            }
        }

        sb.AppendLine(Repeat('─', 72));
        sb.AppendLine($"   Total messages logged: {logged.Count}");
        sb.AppendLine();

        // ── Block 5: Prepared by ──────────────────────────────────────────────
        sb.AppendLine("5. PREPARED BY:");
        sb.AppendLine($"   Name:      {operatorName}");
        sb.AppendLine($"   Callsign:  {operatorCallsign}");
        sb.AppendLine($"   Position:  {icsPosition}");
        sb.AppendLine($"   Date/Time: {now.ToLocalTime():MM/dd/yyyy HH:mm}");
        sb.AppendLine();

        // ── Footer ────────────────────────────────────────────────────────────
        sb.AppendLine(Repeat('═', 72));
        sb.AppendLine(Center("Generated by APRS Command — github.com/KE4CON/APRS-Command", 72));
        sb.AppendLine(Center("ICS 309 — Page 1 of 1", 72));
        sb.AppendLine(Repeat('═', 72));

        return sb.ToString();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────
    private static string Repeat(char c, int n) => new(c, n);
    private static string Center(string s, int width) =>
        s.Length >= width ? s : s.PadLeft((width + s.Length) / 2).PadRight(width);
    private static string Truncate(string s, int max) =>
        s.Length <= max ? s : s[..(max - 1)] + "…";
}
