# ============================================================
# APRS Command — Windows NSIS installer
#
# No Authenticode certificate required.
# SmartScreen will warn on first run — click "More info" then
# "Run anyway". Standard for unsigned open-source software.
#
# Usage (PowerShell):
#   pwsh scripts/make-windows-installer.ps1 [-Version 0.4.0]
#
# Requirements:
#   - .NET 10 SDK
#   - NSIS 3.x (free): https://nsis.sourceforge.io/
#     If not found, the .nsi script is written for manual compile.
# ============================================================
param([string]$Version = "")

$ErrorActionPreference = "Stop"
$ScriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot     = Split-Path -Parent $ScriptDir
$PublishDir   = Join-Path $RepoRoot "artifacts\publish\win-x64"
$InstallerDir = Join-Path $RepoRoot "artifacts\installers"
$NsiFile      = Join-Path $InstallerDir "aprs-command.nsi"
$OutFile      = Join-Path $InstallerDir "APRSCommand-windows-x64-Setup.exe"

# Derive version from git tag if not supplied
if (-not $Version) {
    try {
        $Version = (git -C $RepoRoot describe --tags --abbrev=0 2>$null) -replace '^v', ''
    } catch {}
    if (-not $Version) { $Version = "0.0.0-dev" }
}

# ── 1. Publish ────────────────────────────────────────────────────────────────
if (-not (Test-Path (Join-Path $PublishDir "Aprs.Desktop.exe"))) {
    Write-Host "Publishing win-x64..."
    $proj = Join-Path $RepoRoot "src\Aprs.Desktop\Aprs.Desktop.csproj"
    dotnet publish $proj -c Release -r win-x64 --self-contained true `
        -p:PublishSingleFile=false -p:PublishReadyToRun=true -o $PublishDir
}

New-Item -ItemType Directory -Force -Path $InstallerDir | Out-Null

# ── 2. Write NSIS script ──────────────────────────────────────────────────────
Write-Host "Writing NSIS script..."

# Escape backslashes for NSIS
$PublishNsi   = $PublishDir.Replace('\', '\\')
$OutFileNsi   = $OutFile.Replace('\', '\\')
$LicensePath  = (Join-Path $RepoRoot "LICENSE").Replace('\', '\\')

@"
; APRS Command — Windows Installer
; Generated by scripts/make-windows-installer.ps1
; Requires NSIS 3.x: https://nsis.sourceforge.io/
; Not code-signed. SmartScreen will warn on first run — click More info then Run anyway.

!define APP_NAME    "APRS Command"
!define APP_VERSION "$Version"
!define APP_EXE     "Aprs.Desktop.exe"
!define INST_DIR    "`$PROGRAMFILES64\APRS Command"
!define UNINSTALLER "Uninstall.exe"
!define REG_KEY     "Software\Microsoft\Windows\CurrentVersion\Uninstall\APRSCommand"
!define PUBLISHER   "KE4CON"
!define URL         "https://github.com/KE4CON/APRS-Command"

Name              "`${APP_NAME} `${APP_VERSION}"
OutFile           "$OutFileNsi"
InstallDir        "`${INST_DIR}"
InstallDirRegKey  HKLM "`${REG_KEY}" "InstallLocation"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

!include "MUI2.nsh"
!define MUI_ABORTWARNING

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "$LicensePath"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "APRS Command" SecMain
  SectionIn RO
  SetOutPath "`$INSTDIR"
  File /r "$PublishNsi\\*.*"

  CreateDirectory "`$SMPROGRAMS\`${APP_NAME}"
  CreateShortcut  "`$SMPROGRAMS\`${APP_NAME}\`${APP_NAME}.lnk" "`$INSTDIR\`${APP_EXE}"
  CreateShortcut  "`$SMPROGRAMS\`${APP_NAME}\Uninstall.lnk"    "`$INSTDIR\`${UNINSTALLER}"
  CreateShortcut  "`$DESKTOP\`${APP_NAME}.lnk"                 "`$INSTDIR\`${APP_EXE}"

  WriteRegStr   HKLM "`${REG_KEY}" "DisplayName"     "`${APP_NAME} `${APP_VERSION}"
  WriteRegStr   HKLM "`${REG_KEY}" "UninstallString" "`$INSTDIR\`${UNINSTALLER}"
  WriteRegStr   HKLM "`${REG_KEY}" "InstallLocation" "`$INSTDIR"
  WriteRegStr   HKLM "`${REG_KEY}" "Publisher"       "`${PUBLISHER}"
  WriteRegStr   HKLM "`${REG_KEY}" "DisplayVersion"  "`${APP_VERSION}"
  WriteRegStr   HKLM "`${REG_KEY}" "URLInfoAbout"    "`${URL}"
  WriteRegDWORD HKLM "`${REG_KEY}" "NoModify"        1
  WriteRegDWORD HKLM "`${REG_KEY}" "NoRepair"        1
  WriteUninstaller "`$INSTDIR\`${UNINSTALLER}"
SectionEnd

Section "Uninstall"
  RMDir /r "`$INSTDIR"
  Delete "`$SMPROGRAMS\`${APP_NAME}\`${APP_NAME}.lnk"
  Delete "`$SMPROGRAMS\`${APP_NAME}\Uninstall.lnk"
  RMDir  "`$SMPROGRAMS\`${APP_NAME}"
  Delete "`$DESKTOP\`${APP_NAME}.lnk"
  DeleteRegKey HKLM "`${REG_KEY}"
SectionEnd
"@ | Out-File -Encoding UTF8 -FilePath $NsiFile

Write-Host "  → $NsiFile"

# ── 3. Compile with NSIS if available ────────────────────────────────────────
$makensis = @(
    "C:\Program Files (x86)\NSIS\makensis.exe",
    "C:\Program Files\NSIS\makensis.exe"
) + @((Get-Command makensis -ErrorAction SilentlyContinue)?.Source) |
    Where-Object { $_ -and (Test-Path $_) } |
    Select-Object -First 1

if ($makensis) {
    Write-Host "Compiling with NSIS: $makensis"
    & $makensis $NsiFile
    Write-Host ""
    Write-Host "Done. Installer: $OutFile"
    Write-Host ""
    Write-Host "NOTE: NOT code-signed. SmartScreen will warn on first run."
    Write-Host "  Users click 'More info' then 'Run anyway'."
} else {
    Write-Host ""
    Write-Host "NSIS not found. Install from https://nsis.sourceforge.io/"
    Write-Host "Then run:  makensis `"$NsiFile`""
    Write-Host ""
    Write-Host "NSIS script written to: $NsiFile"
}
